INSERT INTO tipo_refeicoes values (1,'Pequeno-Almoço');
INSERT INTO tipo_refeicoes values (2,'Almoço');
INSERT INTO tipo_refeicoes values (3,'Jantar');

INSERT INTO tipo_ementas values (2,'Entradas');
INSERT INTO tipo_ementas values (3,'Pratos de Peixe');
INSERT INTO tipo_ementas values (4,'Pratos de Carne');
INSERT INTO tipo_ementas values (5,'Sobremesas');

insert into alergias (id_alergia, designacao) values (DEFAULT, 'Pannariaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Tamaricaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Fabaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Asteraceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Poaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Cactaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Poaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Asteraceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Liliaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Dryopteridaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Rosaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Cyperaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Scrophulariaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Brassicaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Illiciaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Melastomataceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Fabaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Polygalaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Cyperaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Brachytheciaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Fabaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Solanaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Campanulaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Dryopteridaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Violaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Saxifragaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Fabaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Brassicaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Amaranthaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Poaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Nyctaginaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Chenopodiaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Liliaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Scrophulariaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Seligeriaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Lichinaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Lycopodiaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Rosaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Cyperaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Parmeliaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Asteraceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Rhamnaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Polygonaceae');
insert into alergias (id_alergia, designacao) values (DEFAULT, 'Gesneriaceae');

insert into clientes (id_cliente, nome) values (DEFAULT, 'Costa');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Abeu');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Teodoor');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Dilly');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Alec');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Kimball');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Yurik');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Trevor');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Lyle');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Janos');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Royall');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Zerk');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Spence');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Gustave');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Claybourne');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Urbain');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Olivier');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Marco');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Rand');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Emmett');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Noam');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Tore');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Virge');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Alonzo');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Lowe');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Cchaddie');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Staford');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Aguistin');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Wallis');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Jamison');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Avictor');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Leonerd');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Gaston');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Abbe');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Brennen');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Tate');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Mortie');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Hashim');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Eberto');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Cheston');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Irvin');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Cyrus');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Fabe');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Kylie');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Major');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Torre');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Kincaid');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Huberto');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Travus');
insert into clientes (id_cliente, nome) values (DEFAULT, 'Gale');

insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Centidel', 'cgiercke0@forbes.com', 910000001, '6531 Southridge Point');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Rhyloo', 'ccamilio1@techcrunch.com', 910000002, '052 Texas Point');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Topicware', 'vbeazer2@psu.edu', 910000003, '0448 Schmedeman Place');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Lazzy', 'rlinner3@twitter.com', 910000004, '37 Beilfuss Avenue');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Brightdog', 'dboick4@nsw.gov.au', 910000005, '93705 Tomscot Place');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skipfire', 'iburtonshaw5@meetup.com', 910000006, '26 Dryden Place');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Tagopia', 'friccardini6@reference.com', 910000007, '243 Bluestem Way');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Oyope', 'amacallester7@facebook.com', 910000008, '3740 Loeprich Drive');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Edgewire', 'lbottinelli8@vimeo.com', 910000009, '39186 Pepper Wood Road');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Oyoba', 'jschmidt9@usda.gov', 910000010, '8089 Bluejay Parkway');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Kwimbee', 'wgemsona@epa.gov', 910000011, '3 Kropf Trail');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skinix', 'rdennessb@163.com', 910000012, '4778 Susan Parkway');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Topicware', 'ubolensc@google.nl', 910000013, '5762 Gale Hill');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Flipstorm', 'dfilmerd@ucoz.com', 910000014, '3 Anthes Pass');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Mita', 'mtallmane@nasa.gov', 910000015, '3 Ludington Street');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Meevee', 'odewittf@discuz.net', 910000016, '066 Carpenter Point');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Twitterlist', 'cevettg@w3.org', 910000017, '9 Sunbrook Center');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Devshare', 'rluardh@gravatar.com', 910000018, '3 Kings Point');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Aivee', 'cwarehami@drupal.org', 910000019, '390 Sloan Hill');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Fanoodle', 'hquinneyj@ask.com', 910000020, '8 Fairview Place');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skidoo', 'tjayesk@oakley.com', 910000021, '9427 Ridgeway Way');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Kaymbo', 'grupell@nps.gov', 910000022, '072 Armistice Lane');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Topicblab', 'bspurlingm@home.pl', 910000023, '220 Dwight Hill');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Dynazzy', 'gcasettin@ucoz.com', 910000024, '63 Waubesa Place');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Shufflester', 'fhusbando@fc2.com', 910000025, '3 Dwight Pass');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Dazzlesphere', 'tadanp@free.fr', 910000026, '35759 American Ash Parkway');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Thoughtbridge', 'ewickmannq@feedburner.com', 910000027, '7 Fairfield Lane');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Meeveo', 'abremleyr@japanpost.jp', 910000028, '5 Lyons Street');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Blogpad', 'wfagans@blog.com', 910000029, '495 Mesta Lane');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Oozz', 'lcrowchet@jalbum.net', 910000030, '3 High Crossing Street');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Gigabox', 'bferranu@blogtalkradio.com', 910000031, '8333 Cherokee Pass');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Eidel', 'aperingv@edublogs.org', 910000032, '440 Del Sol Way');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skyba', 'lcrossgrovew@wikispaces.com', 910000033, '1 Judy Plaza');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Katz', 'ldodsx@who.int', 910000034, '356 Crowley Center');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Cogidoo', 'smerseyy@elpais.com', 910000035, '51810 Schiller Lane');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Innotype', 'gverricoz@mapquest.com', 910000036, '87542 Farragut Trail');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Jaxspan', 'wscourgie10@whitehouse.gov', 910000037, '863 Esker Center');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Livetube', 'plightbown11@google.fr', 910000038, '850 Union Junction');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Ozu', 'igarrould12@mozilla.com', 910000039, '07901 Clarendon Junction');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Quimm', 'zourry13@icio.us', 910000040, '324 Marcy Street');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Yoveo', 'ushepley14@nytimes.com', 910000041, '5 Arapahoe Junction');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Talane', 'hdockrell15@state.gov', 910000042, '7104 Utah Junction');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skimia', 'krawson16@smugmug.com', 910000043, '25 Elgar Circle');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Trilith', 'jfernao17@people.com.cn', 910000044, '0102 Main Circle');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Bluejam', 'mklaaasen18@google.ru', 910000045, '3800 Alpine Way');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skivee', 'eholmyard19@xinhuanet.com', 910000046, '5 Lerdahl Parkway');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Quaxo', 'cleclercq1a@mashable.com', 910000047, '7050 Stone Corner Center');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Dabvine', 'hbree1b@lycos.com', 910000048, '71 Quincy Court');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Podcat', 'ngiacobilio1c@nymag.com', 910000049, '0 Porter Pass');
insert into restaurantes (id_restaurante, nome, email, telefone, morada) values (DEFAULT, 'Skidoo', 'gdehooge1d@latimes.com', 910000050, '694 Mariners Cove Place');

    Table
    SQL

insert into itens (id_iten, designacao) values (DEFAULT, 'Muffin Mix - Oatmeal');
insert into itens (id_iten, designacao) values (DEFAULT, 'Flour - Whole Wheat');
insert into itens (id_iten, designacao) values (DEFAULT, 'Roe - Flying Fish');
insert into itens (id_iten, designacao) values (DEFAULT, 'Pop - Club Soda Can');
insert into itens (id_iten, designacao) values (DEFAULT, 'Bar Special K');
insert into itens (id_iten, designacao) values (DEFAULT, 'Split Peas - Green, Dry');
insert into itens (id_iten, designacao) values (DEFAULT, 'Soup - Campbells, Creamy');
insert into itens (id_iten, designacao) values (DEFAULT, 'Spic And Span All Purpose');
insert into itens (id_iten, designacao) values (DEFAULT, 'Cheese - Provolone');
insert into itens (id_iten, designacao) values (DEFAULT, 'Wine - Prosecco Valdobiaddene');
insert into itens (id_iten, designacao) values (DEFAULT, 'Chicken - Leg / Back Attach');
insert into itens (id_iten, designacao) values (DEFAULT, 'Salt - Seasoned');
insert into itens (id_iten, designacao) values (DEFAULT, 'Flower - Potmums');
insert into itens (id_iten, designacao) values (DEFAULT, 'Filter - Coffee');
insert into itens (id_iten, designacao) values (DEFAULT, 'Raspberries - Frozen');
insert into itens (id_iten, designacao) values (DEFAULT, 'Doilies - 8, Paper');
insert into itens (id_iten, designacao) values (DEFAULT, 'Rice - Brown');
insert into itens (id_iten, designacao) values (DEFAULT, 'Wine - Winzer Krems Gruner');
insert into itens (id_iten, designacao) values (DEFAULT, 'Cheese Cloth No 60');
insert into itens (id_iten, designacao) values (DEFAULT, 'Jam - Strawberry, 20 Ml Jar');
insert into itens (id_iten, designacao) values (DEFAULT, 'Sobe - Orange Carrot');
insert into itens (id_iten, designacao) values (DEFAULT, 'Wine - Rosso Toscano Igt');
insert into itens (id_iten, designacao) values (DEFAULT, 'Soupcontfoam16oz 116con');
insert into itens (id_iten, designacao) values (DEFAULT, 'Sun - Dried Tomatoes');
insert into itens (id_iten, designacao) values (DEFAULT, 'Island Oasis - Magarita Mix');
insert into itens (id_iten, designacao) values (DEFAULT, 'Coconut Milk - Unsweetened');
insert into itens (id_iten, designacao) values (DEFAULT, 'Oven Mitt - 13 Inch');
insert into itens (id_iten, designacao) values (DEFAULT, 'Thyme - Dried');
insert into itens (id_iten, designacao) values (DEFAULT, 'Soup - Knorr, Chicken Noodle');
insert into itens (id_iten, designacao) values (DEFAULT, 'Fireball Whisky');
insert into itens (id_iten, designacao) values (DEFAULT, 'Wine - Lamancha Do Crianza');
insert into itens (id_iten, designacao) values (DEFAULT, 'Red Currants');
insert into itens (id_iten, designacao) values (DEFAULT, 'Shallots');
insert into itens (id_iten, designacao) values (DEFAULT, 'Red Pepper Paste');
insert into itens (id_iten, designacao) values (DEFAULT, 'Wine - Lamancha Do Crianza');
insert into itens (id_iten, designacao) values (DEFAULT, 'French Pastries');
insert into itens (id_iten, designacao) values (DEFAULT, 'Everfresh Products');
insert into itens (id_iten, designacao) values (DEFAULT, 'Cleaner - Bleach');
insert into itens (id_iten, designacao) values (DEFAULT, 'Bananas');
insert into itens (id_iten, designacao) values (DEFAULT, 'Wine - Beaujolais Villages');
insert into itens (id_iten, designacao) values (DEFAULT, 'Chives - Fresh');
insert into itens (id_iten, designacao) values (DEFAULT, 'Crab Brie In Phyllo');
insert into itens (id_iten, designacao) values (DEFAULT, 'Soup - Campbells, Creamy');
insert into itens (id_iten, designacao) values (DEFAULT, 'Chips Potato Reg 43g');
insert into itens (id_iten, designacao) values (DEFAULT, 'Squeeze Bottle');
insert into itens (id_iten, designacao) values (DEFAULT, 'Soup - Campbells');
insert into itens (id_iten, designacao) values (DEFAULT, 'Napkin - Cocktail,beige 2 - Ply');
insert into itens (id_iten, designacao) values (DEFAULT, 'Broom And Broom Rack White');
insert into itens (id_iten, designacao) values (DEFAULT, 'Bread - Dark Rye');
insert into itens (id_iten, designacao) values (DEFAULT, 'Cheese - Victor Et Berthold');

insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 2, 'Demongeot', 945000001);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 2, 'Coombe', 945000002);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 3, 'Knappitt', 945000003);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 4, 'Gissing', 945000004);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 5, 'Wedge', 945000005);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 6, 'Archley', 945000006);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 7, 'Inder', 945000007);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 8, 'Sparway', 945000008);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 9, 'Ronald', 945000009);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 10, 'Staveley', 945000010);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 11, 'Stud', 945000011);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 12, 'Kidney', 945000012);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 13, 'Cattellion', 945000013);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 14, 'Banville', 945000014);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 15, 'Mannock', 945000015);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 16, 'Clears', 945000016);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 17, 'Ewbanche', 945000017);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 18, 'Chamberlaine', 945000018);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 19, 'Kippax', 945000019);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 20, 'Acreman', 945000020);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 21, 'Lever', 945000021);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 22, 'McGuiney', 945000022);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 23, 'Truder', 945000023);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 24, 'Ziems', 945000024);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 25, 'McLice', 945000025);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 26, 'Lethcoe', 945000026);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 27, 'O''Sheilds', 945000027);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 28, 'Patillo', 945000028);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 29, 'Hannond', 945000029);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 30, 'Monk', 945000030);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 31, 'Henrichs', 945000031);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 32, 'Ickowics', 945000032);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 33, 'Slimings', 945000033);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 34, 'Ikringill', 945000034);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 35, 'Coaster', 945000035);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 36, 'Gamble', 945000036);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 37, 'Svanini', 945000037);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 38, 'Padefield', 945000038);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 39, 'Reichartz', 945000039);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 40, 'Dwyr', 945000040);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 41, 'Fairbourn', 945000041);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 42, 'Matschoss', 945000042);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 43, 'Dudin', 945000043);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 44, 'Shulver', 945000044);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 45, 'Lathbury', 945000045);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 46, 'Doggrell', 945000046);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 47, 'Fullilove', 945000047);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 48, 'Crookston', 945000048);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 49, 'Velden', 945000049);
insert into funcionarios (id_funcionario, id_restaurante, nome, telefone) values (DEFAULT, 50, 'Fullard', 945000050);
